package com.talia.multilanguagedemogroup1


/*
 * LanguageUiState
 *
 * This data class stores all the text that is currently
 * displayed on our language screen.
 *
 * Why do we need this?
 *
 * English:
 * -> text comes from values/strings.xml
 *
 * Afrikaans:
 * -> text is automatically generated by ML Kit
 *
 * isiZulu:
 * -> text comes from values-zu/strings.xml
 *
 * When these values change, Compose can recompose the screen
 * and display the new language.
 */
data class LanguageUiState(

    /*
     * Main heading displayed at the top of the screen.
     */
    val screenTitle: String,


    /*
     * Welcome message displayed to the user.
     */
    val welcomeMessage: String,


    /*
     * Short explanation shown underneath the welcome message.
     */
    val description: String,


    /*
     * Label displayed above the language buttons.
     */
    val chooseLanguage: String,


    /*
     * Labels for our language buttons.
     */
    val englishLabel: String,

    val afrikaansLabel: String,

    val zuluLabel: String,


    /*
     * Label used to show the currently selected language.
     */
    val currentLanguageLabel: String,


    /*
     * Label for returning control to the device language.
     */
    val systemLanguageLabel: String
)